CREATE DATABASE exercise_1;
CREATE TABLE `exercise_1`.`emp_1` (
  `EMP_NUM` CHAR(3) NOT NULL,
  `EMP_LNAME` VARCHAR(15) NULL,
  `EMP_FNAME` VARCHAR(15) NULL,
  `EMP_INITIAL` CHAR(1) NULL,
  `EMP_HIREDATE` DATE NULL,
  `JOB_CODE` CHAR(3) NULL,
  PRIMARY KEY (`EMP_NUM`));
  
INSERT INTO `exercise_1`.`emp_1` (`EMP_NUM`, `EMP_LNAME`, `EMP_FNAME`, `EMP_HIREDATE`, `JOB_CODE`) VALUES ('1', 'VARGAS', 'ZEP', '2023-03-10', '502');
INSERT INTO `exercise_1`.`emp_1` (`EMP_NUM`, `EMP_LNAME`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`) VALUES ('2', 'ATIENZA', 'NEIL', 'A', '2023-03-12', '502');
INSERT INTO `exercise_1`.`emp_1` (`EMP_NUM`, `EMP_LNAME`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`) VALUES ('3', 'ROLDAN', 'XIENINA', 'F', '2023-03-16', '502');
INSERT INTO `exercise_1`.`emp_1` (`EMP_NUM`, `EMP_LNAME`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`) VALUES ('4', 'VIRAY', 'DANIEL', 'M', '2023-03-19', '502');
INSERT INTO `exercise_1`.`emp_1` (`EMP_NUM`, `EMP_LNAME`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`) VALUES ('5', 'RABENA', 'EDRIAN', 'B', '2023-03-25', '502');
